server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /tabulator/index.html;
    }

    location /tabulator/ {
        try_files $uri $uri/ /tabulator/index.html;
    }

    location = /tabulator {
        return 301 /tabulator/;
    }
}
